DROP TABLE IF EXISTS H_LENDING_REQUEST_DETAIL_HISTORY;
DROP TABLE IF EXISTS H_EQUIPMENT_HISTORY;
DROP TABLE IF EXISTS H_LENDING_REQUEST_HISTORY;
DROP TABLE IF EXISTS T_LENDING_REQUEST_DETAIL;
DROP TABLE IF EXISTS T_LENDING_REQUEST;
DROP TABLE IF EXISTS M_EQUIPMENT;
DROP TABLE IF EXISTS M_EQUIPMENT_TYPE;
DROP TABLE IF EXISTS M_USER;
DROP SEQUENCE IF EXISTS SEQ_T_LENDING_REQUEST_ID;

CREATE TABLE M_USER (
    USER_ID CHAR(6) NOT NULL,
    USER_NAME VARCHAR(100) NOT NULL,
    ROLE_CODE VARCHAR(20) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    CREATED_BY VARCHAR(64) NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL,
    UPDATED_BY VARCHAR(64) NOT NULL,
    VERSION INT NOT NULL,
    CONSTRAINT PK_M_USER PRIMARY KEY (USER_ID)
);

CREATE INDEX IDX_M_USER_01 ON M_USER (USER_NAME);
CREATE INDEX IDX_M_USER_02 ON M_USER (ROLE_CODE);

CREATE TABLE M_EQUIPMENT_TYPE (
    EQUIPMENT_TYPE_CODE VARCHAR(40) NOT NULL,
    EQUIPMENT_TYPE_NAME VARCHAR(100) NOT NULL,
    DISPLAY_ORDER INT NOT NULL,
    ACTIVE_FLAG BOOLEAN NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    CREATED_BY VARCHAR(64) NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL,
    UPDATED_BY VARCHAR(64) NOT NULL,
    VERSION INT NOT NULL,
    CONSTRAINT PK_M_EQUIPMENT_TYPE PRIMARY KEY (EQUIPMENT_TYPE_CODE),
    CONSTRAINT UK_M_EQUIPMENT_TYPE_01 UNIQUE (EQUIPMENT_TYPE_NAME)
);

CREATE INDEX IDX_M_EQUIPMENT_TYPE_01 ON M_EQUIPMENT_TYPE (DISPLAY_ORDER, ACTIVE_FLAG);

CREATE TABLE M_EQUIPMENT (
    EQUIPMENT_ID BIGINT NOT NULL,
    EQUIPMENT_CODE VARCHAR(30) NOT NULL,
    EQUIPMENT_NAME VARCHAR(100) NOT NULL,
    EQUIPMENT_TYPE VARCHAR(40) NOT NULL,
    STORAGE_LOCATION VARCHAR(100) NOT NULL,
    SYSTEM_REGISTERED_DATE DATE NOT NULL,
    STATUS_CODE VARCHAR(20) NOT NULL,
    REMARKS VARCHAR(500),
    CREATED_AT TIMESTAMP NOT NULL,
    CREATED_BY VARCHAR(64) NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL,
    UPDATED_BY VARCHAR(64) NOT NULL,
    VERSION INT NOT NULL,
    CONSTRAINT PK_M_EQUIPMENT PRIMARY KEY (EQUIPMENT_ID),
    CONSTRAINT UK_M_EQUIPMENT_01 UNIQUE (EQUIPMENT_CODE),
    CONSTRAINT FK_M_EQUIPMENT_01 FOREIGN KEY (EQUIPMENT_TYPE) REFERENCES M_EQUIPMENT_TYPE (EQUIPMENT_TYPE_CODE)
);

CREATE INDEX IDX_M_EQUIPMENT_01 ON M_EQUIPMENT (EQUIPMENT_NAME);
CREATE INDEX IDX_M_EQUIPMENT_02 ON M_EQUIPMENT (EQUIPMENT_TYPE, STATUS_CODE);
CREATE INDEX IDX_M_EQUIPMENT_03 ON M_EQUIPMENT (SYSTEM_REGISTERED_DATE, STATUS_CODE);

CREATE SEQUENCE SEQ_T_LENDING_REQUEST_ID START WITH 2001 INCREMENT BY 1;

CREATE TABLE T_LENDING_REQUEST (
    LENDING_REQUEST_ID BIGINT NOT NULL,
    APPLICANT_USER_ID CHAR(6) NOT NULL,
    REVIEWED_BY_USER_ID CHAR(6),
    RETURN_CONFIRMED_BY_USER_ID CHAR(6),
    STATUS_CODE VARCHAR(30) NOT NULL,
    REQUEST_COMMENT VARCHAR(500),
    REVIEW_COMMENT VARCHAR(500),
    RETURN_REQUEST_COMMENT VARCHAR(500),
    RETURN_CONFIRM_COMMENT VARCHAR(500),
    REQUESTED_AT TIMESTAMP NOT NULL,
    REVIEWED_AT TIMESTAMP,
    RETURN_REQUESTED_AT TIMESTAMP,
    COMPLETED_AT TIMESTAMP,
    CREATED_AT TIMESTAMP NOT NULL,
    CREATED_BY VARCHAR(64) NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL,
    UPDATED_BY VARCHAR(64) NOT NULL,
    VERSION INT NOT NULL,
    CONSTRAINT PK_T_LENDING_REQUEST PRIMARY KEY (LENDING_REQUEST_ID)
);

CREATE INDEX IDX_T_LENDING_REQUEST_01 ON T_LENDING_REQUEST (APPLICANT_USER_ID, STATUS_CODE);
CREATE INDEX IDX_T_LENDING_REQUEST_02 ON T_LENDING_REQUEST (STATUS_CODE);
CREATE INDEX IDX_T_LENDING_REQUEST_03 ON T_LENDING_REQUEST (REVIEWED_BY_USER_ID);

CREATE TABLE T_LENDING_REQUEST_DETAIL (
    LENDING_REQUEST_ID BIGINT NOT NULL,
    EQUIPMENT_ID BIGINT NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    CREATED_BY VARCHAR(64) NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL,
    UPDATED_BY VARCHAR(64) NOT NULL,
    CONSTRAINT PK_T_LENDING_REQUEST_DETAIL PRIMARY KEY (LENDING_REQUEST_ID, EQUIPMENT_ID)
);

CREATE INDEX IDX_T_LENDING_REQUEST_DETAIL_01 ON T_LENDING_REQUEST_DETAIL (EQUIPMENT_ID);

CREATE TABLE H_LENDING_REQUEST_HISTORY (
    OPERATION_ID CHAR(36) NOT NULL,
    LENDING_REQUEST_ID BIGINT NOT NULL,
    COMMAND_SERVICE_ID VARCHAR(64) NOT NULL,
    OPERATED_AT TIMESTAMP NOT NULL,
    CONSTRAINT PK_H_LENDING_REQUEST_HISTORY PRIMARY KEY (OPERATION_ID, LENDING_REQUEST_ID)
);

CREATE INDEX IDX_H_LENDING_REQUEST_HISTORY_01 ON H_LENDING_REQUEST_HISTORY (LENDING_REQUEST_ID, OPERATED_AT);
CREATE INDEX IDX_H_LENDING_REQUEST_HISTORY_02 ON H_LENDING_REQUEST_HISTORY (COMMAND_SERVICE_ID, OPERATED_AT);

CREATE TABLE H_LENDING_REQUEST_DETAIL_HISTORY (
    OPERATION_ID CHAR(36) NOT NULL,
    LENDING_REQUEST_ID BIGINT NOT NULL,
    EQUIPMENT_ID BIGINT NOT NULL,
    COMMAND_SERVICE_ID VARCHAR(64) NOT NULL,
    OPERATED_AT TIMESTAMP NOT NULL,
    CONSTRAINT PK_H_LENDING_REQUEST_DETAIL_HISTORY PRIMARY KEY (OPERATION_ID, LENDING_REQUEST_ID, EQUIPMENT_ID)
);

CREATE INDEX IDX_H_LENDING_REQUEST_DETAIL_HISTORY_01 ON H_LENDING_REQUEST_DETAIL_HISTORY (LENDING_REQUEST_ID, OPERATED_AT);
CREATE INDEX IDX_H_LENDING_REQUEST_DETAIL_HISTORY_02 ON H_LENDING_REQUEST_DETAIL_HISTORY (EQUIPMENT_ID, OPERATED_AT);

CREATE TABLE H_EQUIPMENT_HISTORY (
    OPERATION_ID CHAR(36) NOT NULL,
    EQUIPMENT_ID BIGINT NOT NULL,
    COMMAND_SERVICE_ID VARCHAR(64) NOT NULL,
    OPERATED_AT TIMESTAMP NOT NULL,
    CONSTRAINT PK_H_EQUIPMENT_HISTORY PRIMARY KEY (OPERATION_ID, EQUIPMENT_ID)
);

CREATE INDEX IDX_H_EQUIPMENT_HISTORY_01 ON H_EQUIPMENT_HISTORY (EQUIPMENT_ID, OPERATED_AT);
CREATE INDEX IDX_H_EQUIPMENT_HISTORY_02 ON H_EQUIPMENT_HISTORY (COMMAND_SERVICE_ID, OPERATED_AT);
